# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 21cf540ed6d43945116f74efb27c83c6d26f9f299abe666802958d7f13e11e525b45db8336d17df117ee397a93f8e8b2d0888788547262f627825909a7f93fac

test:
  secret_key_base: e67af9ea18ed5008b4e3a3600b21804abe9210dcb49d48a511aee6255383422ead0abdbe0240b46ff3d1b2012a0ca5fe511798e4d1b2a7d445f656928fdc91db

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
